class DBConstants:
    register_user     = 'INSERT INTO Utilizador (email,password,idCarteira,dataNascimento,nif,isAdmin,isEspecialista) VALUES ((%s),(%s),(%s),(%s),(%s));'
    get_log_info      = 'SELECT email, password FROM Utilizador WHERE email=(%s);'
    add_wallet        = 'INSERT INTO Carteira (saldoCarteira) VALUES(0.00);'
    update_wallet     = 'UPDATE Carteira SET saldoCarteira = saldoCarteira + %s;'
    get_sports        = 'SELECT DISTINCT nomeDesporto FROM Jogo;'
    get_by_sport      = 'SELECT idJogo FROM Jogo WHERE nomeDesporto = (%s);'
    get_game_info     = 'SELECT nomeEquipa, Odd, jogaEmCasa FROM EquipasPorJogo WHERE idJogo = (%s);'
    create_promotion  = 'INSERT INTO Promoção(idJogo, percentagemAumento) Values(%s,%s);'
    boosted_odds      = 'UPDATE EquipasPorJogo SET Odd = Odd * %s WHERE idJogo=%s;'
    get_promotion     = 'SELECT idPromoçao, percentagemAumento, idJogo FROM Promoção WHERE idPromoçao=%s'
    remove_promotion  = 'DELETE FROM Promoção WHERE idPromoçao=%s;'
    get_history_bets  = 'SELECT idAposta, dataAposta, valorApostado FROM Aposta WHERE emailConta=%s;'
    get_history_trans = 'SELECT idTransação, dataTransação, saldoAntes, valorTransação FROM Transação WHERE emailConta=%s;'
    get_balance       = 'SELECT saldoCarteira FROM Carteira WHERE idCarteira = (SELECT idCarteira FROM Utilizador WHERE email=%s);'
    reg_transaction   = 'INSERT INTO Transação(saldoAntes,valorTransação,emailConta,descricao) VALUES(%s,%s,%s,%s)'
    reg_bet           = 'INSERT INTO Aposta(emailConta, valorApostado) VALUES(%s,%s)'
    add_game_to_bet   = 'INSERT INTO JogoPorAposta(idAposta,idJogo,odd,resultadoApostado) VALUES(%s,%s,%s,%s)'
    get_odd_by_game   = 'SELECT Odd FROM EquipasPorJogo WHERE idJogo=%s AND nomeEquipa=%s'
    create_game       = 'INSERT INTO Jogo(idJogo, nomeDesporto, dataJogo) VALUES(%s, %s, %s);'
    add_team          = 'INSERT INTO EquipasPorJogo(nomeEquipa, idJogo, Odd, jogaEmCasa) VALUES(%s,%s,%s,%s);'
    get_last_update   = 'SELECT lastUpdate FROM EquipasPorJogo WHERE idJogo=%s;'
    get_game          = 'SELECT idJogo FROM Jogo WHERE idJogo=%s;'
    update_odds       = 'UPDATE EquipasPorJogo SET Odd=%s WHERE idJogo=%s AND nomeEquipa=%s'
    update_user_field = 'UPDATE Utilizador SET %s=%s WHERE idUser=%s;'
    get_teams_by_game = 'SELECT idJogo, nomeEquipa, Odd, jogaEmCasa from EquipasPorJogo WHERE idJogo=%s'
    get_game_date     = 'SELECT dataJogo FROM Jogo WHERE idJogo=%s'
    

